# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-03 03:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_meetup', to=settings.AUTH_USER_MODEL, verbose_name='관심'),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_meetup', to=settings.AUTH_USER_MODEL, verbose_name='주최자'),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='생성일'),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='desc',
            field=models.TextField(verbose_name='설명'),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='image_file',
            field=models.ImageField(upload_to='%Y/%m/%d', verbose_name='썸네일'),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='modified_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='수정일'),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='title',
            field=models.CharField(max_length=200, verbose_name='제목'),
        ),
    ]
