# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-09 07:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0004_auto_20160403_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='관심'),
        ),
    ]
