# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-07 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0006_auto_20160507_1029'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TagModel',
            new_name='Tag',
        ),
        migrations.AddField(
            model_name='meetup',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags', to='meetup.Tag', verbose_name='태그'),
        ),
    ]
