# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-07 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0008_auto_20160507_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d', verbose_name='썸네일'),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='meetup.Tag', verbose_name='태그'),
        ),
    ]
