# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-07 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0010_auto_20160507_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d', verbose_name='썸네일'),
        ),
    ]
