# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-07 15:46
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('meetup', '0011_auto_20160507_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetup',
            name='tags',
        ),
        migrations.AddField(
            model_name='meetup',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
