# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-08 02:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0012_auto_20160507_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='meetup',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
