# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-14 10:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetup', '0013_auto_20160508_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='join',
            field=models.ManyToManyField(blank=True, related_name='join_meetup', to=settings.AUTH_USER_MODEL, verbose_name='참석'),
        ),
    ]
