# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-14 10:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetup', '0014_meetup_join'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetup',
            old_name='join',
            new_name='join_users',
        ),
        migrations.RemoveField(
            model_name='meetup',
            name='likes',
        ),
        migrations.AddField(
            model_name='meetup',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_meetup', to=settings.AUTH_USER_MODEL, verbose_name='관심'),
        ),
    ]
