# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-15 07:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0015_auto_20160514_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='meetup_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='모임일'),
        ),
    ]
