# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 09:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(default=datetime.datetime(2016, 2, 17, 9, 44, 55, 969744, tzinfo=utc), upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='nickname',
            field=models.CharField(default='', max_length=10, verbose_name='닉네임'),
        ),
    ]
