# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, verbose_name='별명'),
        ),
    ]
