# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20160217_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='image/avatar/'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='nickname',
            field=models.CharField(default='', max_length=10, unique=True, verbose_name='닉네임'),
        ),
    ]
