# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20160217_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='nickname',
            field=models.CharField(default='', max_length=10, verbose_name='닉네임'),
        ),
    ]
