# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-08 02:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetup', '0013_auto_20160508_0224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2000, verbose_name='댓글')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='생성일')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_author', to=settings.AUTH_USER_MODEL, verbose_name='이름')),
                ('meetup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='meetup.Meetup', verbose_name='밋업')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
